#!/usr/bin/env bash
# A Bash script that prints a message indefinitely and handles SIGTERM

handle_sigterm() {
    echo "I am invincible!!!"
    return 0   # signals handled correctly
}

trap 'handle_sigterm' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
