#!/usr/bin/env bash
# A Bash script that prints a message indefinitely and handles SIGTERM

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM and call the handler
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
